# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helloworld124_pb2 as helloworld124__pb2


class LinearRegressionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainModel = channel.unary_stream(
                '/helloworld.LinearRegression/TrainModel',
                request_serializer=helloworld124__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=helloworld124__pb2.TrainModelResponse.FromString,
                )


class LinearRegressionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinearRegressionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainModel': grpc.unary_stream_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=helloworld124__pb2.TrainModelRequest.FromString,
                    response_serializer=helloworld124__pb2.TrainModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.LinearRegression', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LinearRegression(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/helloworld.LinearRegression/TrainModel',
            helloworld124__pb2.TrainModelRequest.SerializeToString,
            helloworld124__pb2.TrainModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
