# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld1.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11helloworld1.proto\x12\nhelloworld\"\x1e\n\tGradients\x12\x11\n\tgradients\x18\x01 \x03(\x02\"\'\n\x12\x45ncryptedGradients\x12\x11\n\tgradients\x18\x01 \x03(\x02\x32Y\n\x06PartyA\x12O\n\x16SendEncryptedGradients\x12\x15.helloworld.Gradients\x1a\x1e.helloworld.EncryptedGradientsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GRADIENTS']._serialized_start=33
  _globals['_GRADIENTS']._serialized_end=63
  _globals['_ENCRYPTEDGRADIENTS']._serialized_start=65
  _globals['_ENCRYPTEDGRADIENTS']._serialized_end=104
  _globals['_PARTYA']._serialized_start=106
  _globals['_PARTYA']._serialized_end=195
# @@protoc_insertion_point(module_scope)
