# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helloworld1_pb2 as helloworld1__pb2


class PartyAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEncryptedGradients = channel.unary_unary(
                '/helloworld.PartyA/SendEncryptedGradients',
                request_serializer=helloworld1__pb2.Gradients.SerializeToString,
                response_deserializer=helloworld1__pb2.EncryptedGradients.FromString,
                )


class PartyAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEncryptedGradients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartyAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEncryptedGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEncryptedGradients,
                    request_deserializer=helloworld1__pb2.Gradients.FromString,
                    response_serializer=helloworld1__pb2.EncryptedGradients.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.PartyA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PartyA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEncryptedGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.PartyA/SendEncryptedGradients',
            helloworld1__pb2.Gradients.SerializeToString,
            helloworld1__pb2.EncryptedGradients.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
