# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld124.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13helloworld124.proto\x12\nhelloworld\"E\n\x11TrainModelRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\x0f\n\x07weights\x18\x02 \x03(\x02\x12\r\n\x05label\x18\x03 \x01(\x02\";\n\x12TrainModelResponse\x12\x0c\n\x04loss\x18\x01 \x01(\x02\x12\x17\n\x0fupdated_weights\x18\x02 \x03(\x02\x32\x61\n\x10LinearRegression\x12M\n\nTrainModel\x12\x1d.helloworld.TrainModelRequest\x1a\x1e.helloworld.TrainModelResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld124_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRAINMODELREQUEST']._serialized_start=35
  _globals['_TRAINMODELREQUEST']._serialized_end=104
  _globals['_TRAINMODELRESPONSE']._serialized_start=106
  _globals['_TRAINMODELRESPONSE']._serialized_end=165
  _globals['_LINEARREGRESSION']._serialized_start=167
  _globals['_LINEARREGRESSION']._serialized_end=264
# @@protoc_insertion_point(module_scope)
